name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - name: Print all yaml files
      run: find . -name *.yml
    - name: Yaml lint
      run: yamllint .
